import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Image from "next/image";
import Navbar from "../components/navbar";
import CompanyLogo from "../components/company-logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body clasName={inter.clasName}>{children}</body> */}

      <body
        className={`${inter.className} text-white font-poppins bg-flysha-black`}
      >
        {children}
      </body>
    </html>
  );
}
